#!/bin/bash
if ! [ -x "$(command -v git)" ]; then
  echo 'Error: git is not installed.' >&2
  exit 1
else
  git clone https://github.com/chamunks/docker-support.git /usr/local/src/docker-support
  cp -v /usr/local/src/docker-support/bin/* /bin/
fi
